#!/bin/sh

# TODO Remove this from the postinst of any version that is not updating Django
# Remove .pyo's so Django uninstalls properly (See https://github.com/pypa/pip/issues/2209)
echo "Removing Django's .pyo files to aid upgrade"
find /usr/local/lib/python2.7/dist-packages/django/ -name '*.pyo' -delete

pip install --upgrade -r /usr/share/archivematica/archivematicaCommon/requirements.txt

#DEBHELPER#
