#!/usr/bin/dh-exec

etc/* /etc/archivematica/MCPServer/
lib/* /usr/lib/archivematica/MCPServer/
init/* /etc/init/
share/* /usr/share/archivematica/

share/mysql => /usr/share/dbconfig-common/data/archivematica-mcp-server/install/mysql
share/1.1.0 => /usr/share/dbconfig-common/data/archivematica-mcp-server/upgrade/mysql/1.1.0
share/1.2.0 => /usr/share/dbconfig-common/data/archivematica-mcp-server/upgrade/mysql/1.2.0
share/1.3.0 => /usr/share/dbconfig-common/data/archivematica-mcp-server/upgrade/mysql/1.3.0
share/1.4.0 => /usr/share/dbconfig-common/data/archivematica-mcp-server/upgrade/mysql/1:1.4.0
share/1.4.1 => /usr/share/dbconfig-common/data/archivematica-mcp-server/upgrade/mysql/1:1.4.1
