#!/bin/sh
# source debconf stuff
. /usr/share/debconf/confmodule
. /usr/share/dbconfig-common/dpkg/postinst

dbc_go archivematica-mcp-server $@

userID=`id -u archivematica`

if [ "${userID}" = 333 ]; then
  echo "User archivematica exists"
else
  adduser --uid 333 --group --system --home /var/lib/archivematica/ archivematica
fi

if [ -d /var/archivematica/sharedDirectory ]; then
  echo "/var/archivematica/sharedDirectory exists"
else
  echo "/var/archivematica/sharedDirectory doesn't exist... creating..."
  mkdir -p /var/archivematica/sharedDirectory/
  rsync -a /usr/share/archivematica/sharedDirectoryStructure/* /var/archivematica/sharedDirectory/.
fi

chown -R archivematica:archivematica /var/archivematica/sharedDirectory/

logdir=/var/log/archivematica/MCPServer
sudo mkdir -p $logdir
sudo chown -R archivematica:archivematica $logdir
sudo chmod -R g+s $logdir
sudo chmod -R g+w $logdir

/usr/share/archivematica/postinstSharedWithDev

#DEBHELPER#
