#!/bin/sh
# source debconf stuff
. /usr/share/debconf/confmodule
. /usr/share/dbconfig-common/dpkg/postinst

dbc_go archivematica-mcp-server $@

# Create sharedDirectory and rsync content
mkdir -p /var/archivematica/sharedDirectory/
rsync -a /usr/share/archivematica/sharedDirectoryStructure/* /var/archivematica/sharedDirectory/.

chown -R archivematica:archivematica /var/archivematica/

/usr/share/archivematica/postinstSharedWithDev

#DEBHELPER#

