from django.http import HttpResponse

class HttpCreated(HttpResponse): ...
class HttpAccepted(HttpResponse): ...
class HttpNoContent(HttpResponse): ...
class HttpMultipleChoices(HttpResponse): ...
class HttpSeeOther(HttpResponse): ...
class HttpNotModified(HttpResponse): ...
class HttpBadRequest(HttpResponse): ...
class HttpUnauthorized(HttpResponse): ...
class HttpForbidden(HttpResponse): ...
class HttpNotFound(HttpResponse): ...
class HttpMethodNotAllowed(HttpResponse): ...
class HttpNotAcceptable(HttpResponse): ...
class HttpConflict(HttpResponse): ...
class HttpGone(HttpResponse): ...
class HttpUnsupportedMediaType(HttpResponse): ...
class HttpUnprocessableEntity(HttpResponse): ...
class HttpTooManyRequests(HttpResponse): ...
class HttpApplicationError(HttpResponse): ...
class HttpNotImplemented(HttpResponse): ...
