from datetime import datetime
from typing import ClassVar

from django.contrib.auth.models import User
from django.db.models import Manager
from django.db.models import Model

class ApiAccess(Model):
    objects: ClassVar[Manager[ApiAccess]]

    @property
    def identifier(self) -> str: ...
    @property
    def url(self) -> str: ...
    @property
    def request_method(self) -> str: ...
    @property
    def accessed(self) -> int: ...
    def save(self, *args: object, **kwargs: object) -> None: ...

class ApiKey(Model):
    objects: ClassVar[Manager[ApiKey]]

    @property
    def user(self) -> User: ...
    @property
    def key(self) -> str: ...
    @property
    def created(self) -> datetime: ...
    def save(self, *args: object, **kwargs: object) -> None: ...
    def generate_key(self) -> str: ...

def create_api_key(
    sender: type[Model], instance: Model, created: bool, **kwargs: object
) -> None: ...
