# -*- coding: utf-8 -*-
"""Migration generated by Django 1.11.29."""
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [("main", "0076_version_number")]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_id",
            field=django_extensions.db.fields.UUIDField(
                auto=False, db_column="eventIdentifierUUID", null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="microservicechainlink",
            field=django_extensions.db.fields.UUIDField(
                auto=False, blank=True, db_column="MicroServiceChainLinksPK", null=True
            ),
        ),
        migrations.AlterField(
            model_name="siparrange",
            name="file_uuid",
            field=django_extensions.db.fields.UUIDField(
                auto=False, blank=True, default=None, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="siparrange",
            name="transfer_uuid",
            field=django_extensions.db.fields.UUIDField(
                auto=False, blank=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="unitvariable",
            name="microservicechainlink",
            field=django_extensions.db.fields.UUIDField(
                auto=False, blank=True, db_column="microServiceChainLink", null=True
            ),
        ),
    ]
