repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: pretty-format-json
    args: [--no-ensure-ascii, --autofix]
    files: |
      (?x)^(
        src/archivematica/MCPServer/assets/.*\.json|
        src/archivematica/(MCPClient|MCPServer|dashboard)/install/.*\.json
      )
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.16.4
  hooks:
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix]
  - id: ruff-format
- repo: https://github.com/adamchainz/django-upgrade
  rev: "1.32.0"
  hooks:
  - id: django-upgrade
    args: [--target-version, "5.2"]
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.49.1
  hooks:
  - id: markdownlint
    exclude: |
      (?x)^(
        ISSUE_TEMPLATE\.md|
        src/archivematica/dashboard/media/vendor/.*
      )
- repo: https://github.com/thlorenz/doctoc
  rev: v2.5.0
  hooks:
  - id: doctoc
    files: |
      (?x)^(
        (CONTRIBUTING|SECURITY).*\.md|
        hack/README\.md|
        src/archivematica/(MCPServer|MCPClient|dashboard)/install/README\.md
      )
- repo: https://github.com/citation-file-format/cffconvert
  # Current "2.0.0" git tag does not work because of
  # https://github.com/citation-file-format/cffconvert/issues/375
  rev: 054bda51dbe278b3e86f27c890e3f3ac877d616c
  hooks:
    - id: validate-cff
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v2.3.1
  hooks:
  - id: mypy
    # Override upstream args to omit --ignore-missing-imports on purpose.
    args: ["--scripts-are-modules"]
    # Let mypy own target selection so hook and standalone runs use the same files.
    pass_filenames: false
    additional_dependencies:
    # Most of these dependencies are necessary because django-stubs initializes
    # Django's runtime to extract information about the models.
    - agentarchives
    - amclient
    - bagit
    - clamav-client
    - django-auth-ldap
    - django-autoslug
    - django-cas-ng
    - django-csp
    - django-forms-bootstrap
    - django-shibboleth-remoteuser @ git+https://github.com/artefactual-labs/django-shibboleth-remoteuser.git@f08a7864d6130416c352981ccf318fff0fd5be58
    - django-stubs-ext
    - "django-stubs>=6,<7"
    - django-tastypie
    - elasticsearch>=8.0.0,<9.0.0
    - gearman3 @ git+https://github.com/artefactual-labs/python-gearman.git@b68efc868c7a494dd6a2d2e820fb098a6da9f797
    - inotify-simple
    - jsonfield
    - lazy-paged-sequence
    - metsrw
    - mozilla-django-oidc
    - orjson
    - playwright
    - prometheus-client
    - pyjwt
    - pytest
    - pytest-django
    - types-gunicorn
    - types-jsonschema
    - types-lxml
    - types-python-dateutil
    - types-requests
    - unidecode
- repo: https://github.com/tcort/markdown-link-check
  rev: v3.15.0
  hooks:
  - id: markdown-link-check
    stages: [manual]
    args: [--quiet, --config, .markdown-link-check.json]
    exclude: |
      (?x)^(
        src/archivematica/dashboard/media/vendor/.*\.md|
        RELEASENOTES.md
      )
