#!/bin/bash

# This file is part of Archivematica.
#
# Copyright 2010-2013 Artefactual Systems Inc. <http://artefactual.com>
#
# Archivematica is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Archivematica is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Archivematica.  If not, see <http://www.gnu.org/licenses/>.

# @package Archivematica
# @author Joseph Perry <joseph@artefactual.com>
# @version svn: $Id$


colour () { "$@" 2>&1>&3|sed 's,.*,\x1B[31m&\x1B[0m,'>&2;} 3>&1




function database-dump() {
  part="database-dump"
  echo -n "\"Would you like to ${part}?\" (y/N) "
  read a
  if [[ $a == "Y" || $a == "y" ]]; then
    echo "Doing ${part} ..."
    cd localDevSetup/
    colour ./DBDumper.sh
    cd ..
  else
          echo "not going to ${part}"
  fi
}


function git-commit() {
  part="commit to git origin master"
  sleep 1
  git status
  echo -n "\"Would you like to ${part}?\" (y/N) "
  read a
  if [[ $a == "Y" || $a == "y" ]]; then
    echo "Doing ${part} ..."
    echo not implemented
    colour git pull origin master      
    
  else
          echo "not going to ${part}"
  fi
}


# Run only one function if given
if [ ! -z ${1} ]; then
  ${1}
  exit
fi


database-dump
git-commit


