[mypy]

# Avoid name clashing of the settings modules and
# provide better control for per-module options.
explicit_package_bases = True

strict = True
check_untyped_defs = False
disallow_untyped_defs = False
disallow_subclassing_any = False
disallow_untyped_calls = False

[mypy-src.MCPClient.*]
disallow_untyped_calls = True

[mypy-tests.MCPClient.*]
disallow_untyped_calls = True

[mypy-src.MCPServer.*]
disallow_untyped_calls = True

[mypy-tests.MCPServer.*]
disallow_untyped_calls = True

[mypy-src.dashboard.*]
disallow_untyped_calls = True
 
[mypy-tests.dashboard.*]
disallow_untyped_calls = True