[tool.pytest.ini_options]
addopts = "--reuse-db -p no:cacheprovider"
DJANGO_SETTINGS_MODULE="settings.test"
norecursedirs = ".svn _build tmp* node_modules bower_components share .tox"

[tool.coverage.run]
omit = [
    "**/src/archivematica/common/externals/*",
    "**/migrations/*",
    "**/south_migrations/*",
    "**/management/commands/*",
    "**/settings/*",
    "**/tests/*",
    "**/wsgi.py",
    "**/manage.py",
]
include = [
    "**/src/archivematica/*",
]
branch = true

[tool.ruff.lint]
# Rule reference: https://docs.astral.sh/ruff/rules/
select = [
    "B",
    "C4",
    "E",
    "F",
    "I",
    "UP",
    "W",
]
ignore = [
    "B018",
    "B904",
    "E402",
    "E501",
    "UP031",
]

[tool.ruff.lint.per-file-ignores]
"src/*/settings/*" = ["F403"]
"src/*/dashboard/settings/*" = ["F405"]

[tool.ruff.lint.isort]
force-single-line = true

[tool.mypy]
explicit_package_bases = true
warn_redundant_casts = true
warn_unused_configs = true

[[tool.mypy.overrides]]
module = [
    "src.archivematica.common.executeOrRunSubProcess",
    "src.archivematica.MCPClient.client.*",
    "src.archivematica.MCPClient.clientScripts.characterize_file",
    "src.archivematica.MCPClient.clientScripts.has_packages",
    "src.archivematica.MCPClient.clientScripts.identify_file_format",
    "src.archivematica.MCPClient.clientScripts.normalize",
    "src.archivematica.MCPClient.clientScripts.policy_check",
    "src.archivematica.MCPClient.clientScripts.transcribe_file",
    "src.archivematica.MCPClient.clientScripts.validate_file",
    "tests.common.test_execute_functions",
    "tests.dashboard.fpr.test_views",
    "tests.dashboard.test_oidc",
    "tests.integration.test_oidc_auth",
    "tests.MCPClient.conftest",
    "tests.MCPClient.test_characterize_file",
    "tests.MCPClient.test_has_packages",
    "tests.MCPClient.test_identify_file_format",
    "tests.MCPClient.test_normalize",
    "tests.MCPClient.test_policy_check",
    "tests.MCPClient.test_transcribe_file",
    "tests.MCPClient.test_validate_file",
]
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
no_implicit_reexport = true
strict_equality = true
warn_return_any = true
warn_unused_ignores = true

[tool.tox]
legacy_tox_ini = """
    [tox]
    skipsdist = True
    envlist =
        archivematica-common
        dashboard
        mcp-server
        mcp-client
        storage-service
        migrations-dashboard
        migrations-storage-service
        linting

    [testenv]
    skip_install = True
    deps = -r{toxinidir}/requirements-dev.txt
    commands = py.test {posargs}
    allowlist_externals =
        bash
        find
    setenv =
        # General
        LOGNAME = user
        DJANGO_SETTINGS_MODULE = {env:DJANGO_SETTINGS_MODULE:settings.test}
        PYTEST_ADDOPTS = {env:PYTEST_ADDOPTS:}
        SRC_DIR = {toxinidir}/src/archivematica
        HACK_DIR = {toxinidir}/hack
        # Archivematica Common
        ARCHIVEMATICA_COMMON_DIR = {env:SRC_DIR}/common
        # Dashboard
        DASHBOARD_DIR = {env:SRC_DIR}/dashboard
        DASHBOARD_PYTHONPATH = {env:DASHBOARD_DIR}:{env:ARCHIVEMATICA_COMMON_DIR}
        # MCP Server
        MCPSERVER_DIR = {env:SRC_DIR}/MCPServer
        MCPSERVER_PYTHONPATH = {env:MCPSERVER_DIR}:{env:ARCHIVEMATICA_COMMON_DIR}:{env:DASHBOARD_DIR}
        # MCP Client
        MCPCLIENT_DIR = {env:SRC_DIR}/MCPClient
        MCPCLIENT_PYTHONPATH = {env:MCPCLIENT_DIR}:{env:MCPCLIENT_DIR}/clientScripts:{env:ARCHIVEMATICA_COMMON_DIR}:{env:DASHBOARD_DIR}
        # Storage Service
        STORAGE_SERVICE_ROOT = {env:HACK_DIR}/submodules/archivematica-storage-service
        STORAGE_SERVICE_DIR = {env:STORAGE_SERVICE_ROOT}/storage_service
        STORAGE_SERVICE_PYTHONPATH = {env:STORAGE_SERVICE_DIR}:{env:STORAGE_SERVICE_DIR}/storage_service
        # TOXENV-specific
        archivematica-common: PYTHONPATH = {env:DASHBOARD_PYTHONPATH}
        dashboard: PYTHONPATH = {env:DASHBOARD_PYTHONPATH}
        mcp-server: PYTHONPATH = {env:MCPSERVER_PYTHONPATH}
        mcp-client: PYTHONPATH = {env:MCPCLIENT_PYTHONPATH}
        storage-service: PYTHONPATH = {env:STORAGE_SERVICE_PYTHONPATH}
        migrations-dashboard: PYTHONPATH = {env:DASHBOARD_PYTHONPATH}
        migrations-storage-service: PYTHONPATH = {env:STORAGE_SERVICE_PYTHONPATH}
        # Setting HOME prevents Python's pwd module to ask for a real uid inside
        # the container, and using {temp_dir} allows caching the pre-commit
        # dependencies in the tox host
        linting: HOME = {temp_dir}/user
    changedir =
        archivematica-common: {toxinidir}/tests/common
        dashboard: {toxinidir}/tests/dashboard
        mcp-server: {toxinidir}/tests/MCPServer
        mcp-client: {toxinidir}/tests/MCPClient
        storage-service: {env:STORAGE_SERVICE_ROOT}

    [testenv:storage-service]
    deps =
        -r{env:STORAGE_SERVICE_ROOT}/requirements-dev.txt

    [testenv:migrations-dashboard]
    commands = django-admin makemigrations --check --dry-run

    [testenv:migrations-storage-service]
    deps = {[testenv:storage-service]deps}
    commands = {[testenv:migrations-dashboard]commands}

    [testenv:linting]
    basepython = python3
    deps = pre-commit
    commands = pre-commit run --all-files --show-diff-on-failure
"""
