from types import TracebackType

_MockLDAPAttributeMap = dict[str, list[str]]
_MockLDAPDirectory = dict[str, _MockLDAPAttributeMap]

URI_DEFAULT: str

class LDAPObject:
    directory: _MockLDAPDirectory
    async_results: list[object]
    options: dict[int, object]
    tls_enabled: bool
    bound_as: str | None

    def __init__(self, directory: _MockLDAPDirectory) -> None: ...
    def initialize(self, *args: object, **kwargs: object) -> None: ...
    def get_option(self, option: int) -> object: ...
    def set_option(self, option: int, invalue: object) -> None: ...
    def simple_bind_s(
        self,
        who: str = ...,
        cred: str = ...,
    ) -> tuple[int, list[object]]: ...
    def search(
        self,
        base: str,
        scope: int,
        filterstr: str = ...,
        attrlist: list[str] | None = ...,
        attrsonly: int = ...,
    ) -> int: ...
    def result(
        self,
        msgid: int,
        all: int = ...,
        timeout: float | None = ...,
    ) -> tuple[int, list[tuple[str, _MockLDAPAttributeMap]]]: ...
    def search_s(
        self,
        base: str,
        scope: int,
        filterstr: str = ...,
        attrlist: list[str] | None = ...,
        attrsonly: int = ...,
    ) -> list[tuple[str, _MockLDAPAttributeMap]]: ...
    def start_tls_s(self) -> None: ...
    def compare_s(self, dn: str, attr: str, value: str) -> int: ...
    def modify_s(self, dn: str, mod_attrs: object) -> None: ...
    def add_s(self, dn: str, record: _MockLDAPAttributeMap) -> None: ...
    def rename_s(
        self,
        dn: str,
        newrdn: str,
        newsuperior: str | None = ...,
    ) -> None: ...
    def delete_s(self, dn: str) -> None: ...
    def unbind(self) -> None: ...
    def unbind_s(self) -> None: ...
    def whoami_s(self) -> str: ...
    def passwd_s(
        self,
        user: str,
        oldpw: str,
        newpw: str,
        serverctrls: object = ...,
        clientctrls: object = ...,
    ) -> object: ...

class MockLdap:
    def __init__(self, directory: _MockLDAPDirectory | None = ...) -> None: ...
    def __getitem__(self, uri: str) -> LDAPObject: ...
    def set_directory(self, directory: _MockLDAPDirectory, uri: str = ...) -> None: ...
    def start(self, path: str = ...) -> None: ...
    def stop(self, path: str = ...) -> None: ...
    def stop_all(self) -> None: ...
    def initialize(self, uri: str, *args: object, **kwargs: object) -> LDAPObject: ...
    def __enter__(self) -> MockLdap: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...
