#!/usr/bin/env python
# -*- coding: utf8

"""validate_mets.py

Validate METS/PREMIS generated by Generate METS XML scripts during ingest.
"""

from __future__ import absolute_import, unicode_literals

import os
import sys


def concurrent_instances():
    return 1


def call(jobs):
    """Primary entry point for this script.

    We will receive the following arguments that we can do something with:

        \"%SIPDirectory%METS.%SIPUUID%.xml\"
        \"%SIPLogsDirectory%\"

    """
    for job in jobs:
        with job.JobContext():
            job.pyprint(
                "We eventually want to validate (%SIPDirectory%METS.%SIPUUID%.xml):",
                job.args[1],
            )

            log_dir = job.args[2]
            log_name = "picturae_training.log"
            log_file = os.path.join(log_dir, log_name)

            job.pyprint("Writing a log file to", log_file, "directory", file=sys.stderr)
            with open(log_file, "w") as demo_log:
                demo_log.write("Let's put something useful in here.\n")
