// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package mysql

import (
	"context"
)

type Querier interface {
	CleanUpActiveJobs(ctx context.Context) error
	CleanUpActiveSIPs(ctx context.Context) error
	CleanUpActiveTasks(ctx context.Context) error
	CleanUpActiveTransfers(ctx context.Context) error
	CleanUpAwaitingJobs(ctx context.Context) error
	CreateJob(ctx context.Context, arg *CreateJobParams) error
}

var _ Querier = (*Queries)(nil)
