# Generated by Django 4.2.11 on 2024-04-11 08:19
"""Unpickle target in the access table."""

import pickle

from django.db import migrations


def data_migration_up(apps, _):
    """Unpickle Access.target."""
    access = apps.get_model("main", "Access")
    for item in access.objects.all():
        if item.target:
            try:
                item.target = pickle.loads(item.target.encode()).get("target", "")
                item.save()
            except Exception:
                pass


def data_migration_down(apps, _):
    """Pickle Access.target."""
    access = apps.get_model("main", "Access")
    for item in access.objects.all():
        if item.target:
            item.target = pickle.dumps({"target": item.target}, protocol=0).decode()
            item.save()


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0082_use_uuidfield"),
    ]

    operations = [migrations.RunPython(data_migration_up, data_migration_down)]
