---

services:
  archivematica-acceptance-tests:
    build:
      context: "./submodules/archivematica-acceptance-tests"
      dockerfile: "Dockerfile"
    security_opt:
      - "seccomp:unconfined"
    volumes:
      - "/dev/shm:/dev/shm"
      - "./submodules/archivematica-acceptance-tests:/home/archivematica/acceptance-tests:rw"
      - "./submodules/archivematica-sampledata:/home/archivematica/archivematica-sampledata:ro"
      - "archivematica_pipeline_data:/var/archivematica/sharedDirectory:ro"
    links:
      - "nginx"
