---

services:

  archivematica-dashboard:
    environment:
      ARCHIVEMATICA_DASHBOARD_DASHBOARD_SESSION_COOKIE_SAMESITE: "Lax"
      ARCHIVEMATICA_DASHBOARD_OIDC_AUTHENTICATION: "true"
      OIDC_USE_PKCE: "true"
      OIDC_PKCE_CODE_CHALLENGE_METHOD: "S256"
      OIDC_RP_CLIENT_ID: "am-dashboard"
      OIDC_RP_CLIENT_SECRET: "example-secret"
      OIDC_OP_AUTHORIZATION_ENDPOINT: "http://keycloak:8080/realms/demo/protocol/openid-connect/auth"
      OIDC_OP_TOKEN_ENDPOINT: "http://keycloak:8080/realms/demo/protocol/openid-connect/token"
      OIDC_OP_USER_ENDPOINT: "http://keycloak:8080/realms/demo/protocol/openid-connect/userinfo"
      OIDC_OP_JWKS_ENDPOINT: "http://keycloak:8080/realms/demo/protocol/openid-connect/certs"
      OIDC_OP_LOGOUT_ENDPOINT: "http://keycloak:8080/realms/demo/protocol/openid-connect/logout"
      OIDC_OP_SET_ROLES_FROM_CLAIMS: "true"
      OIDC_OP_ROLE_CLAIM_PATH: "realm_access.roles"
      OIDC_ROLE_CLAIM_ADMIN: "admin"
      OIDC_ROLE_CLAIM_DEFAULT: "default"
      OIDC_ACCESS_ATTRIBUTE_MAP: >
        {"given_name": "first_name", "family_name": "last_name", "realm_access": "realm_access"}
      OIDC_SECONDARY_PROVIDER_NAMES: "secondary"
      OIDC_RP_CLIENT_ID_SECONDARY: "am-dashboard-secondary"
      OIDC_RP_CLIENT_SECRET_SECONDARY: "example-secret-secondary"
      OIDC_OP_AUTHORIZATION_ENDPOINT_SECONDARY: "http://keycloak:8080/realms/secondary/protocol/openid-connect/auth"
      OIDC_OP_TOKEN_ENDPOINT_SECONDARY: "http://keycloak:8080/realms/secondary/protocol/openid-connect/token"
      OIDC_OP_USER_ENDPOINT_SECONDARY: "http://keycloak:8080/realms/secondary/protocol/openid-connect/userinfo"
      OIDC_OP_JWKS_ENDPOINT_SECONDARY: "http://keycloak:8080/realms/secondary/protocol/openid-connect/certs"
      OIDC_OP_LOGOUT_ENDPOINT_SECONDARY: "http://keycloak:8080/realms/secondary/protocol/openid-connect/logout"
      OIDC_OP_SET_ROLES_FROM_CLAIMS_SECONDARY: "true"
      OIDC_OP_ROLE_CLAIM_PATH_SECONDARY: "realm_access.roles"
      OIDC_ROLE_CLAIM_ADMIN_SECONDARY: "admin-secondary"
      OIDC_ROLE_CLAIM_DEFAULT_SECONDARY: "default-secondary"
      OIDC_ACCESS_ATTRIBUTE_MAP_SECONDARY: >
        {"given_name": "first_name", "family_name": "last_name", "realm_access": "realm_access"}
      OIDC_RP_SIGN_ALGO: "RS256"
    depends_on:
      elasticsearch:
        condition: service_healthy
        restart: true
      keycloak:
        condition: service_started

  archivematica-storage-service:
    environment:
      SESSION_COOKIE_SAMESITE: "Lax"
      SS_OIDC_AUTHENTICATION: "true"
      OIDC_USE_PKCE: "true"
      OIDC_PKCE_CODE_CHALLENGE_METHOD: "S256"
      OIDC_RP_CLIENT_ID: "am-storage-service"
      OIDC_RP_CLIENT_SECRET: "example-secret"
      OIDC_OP_AUTHORIZATION_ENDPOINT: "http://keycloak:8080/realms/demo/protocol/openid-connect/auth"
      OIDC_OP_TOKEN_ENDPOINT: "http://keycloak:8080/realms/demo/protocol/openid-connect/token"
      OIDC_OP_USER_ENDPOINT: "http://keycloak:8080/realms/demo/protocol/openid-connect/userinfo"
      OIDC_OP_JWKS_ENDPOINT: "http://keycloak:8080/realms/demo/protocol/openid-connect/certs"
      OIDC_OP_LOGOUT_ENDPOINT: "http://keycloak:8080/realms/demo/protocol/openid-connect/logout"
      OIDC_OP_SET_ROLES_FROM_CLAIMS: "true"
      OIDC_OP_ROLE_CLAIM_PATH: "realm_access.roles"
      OIDC_ROLE_CLAIM_ADMIN: "admin"
      OIDC_ROLE_CLAIM_MANAGER: "manager"
      OIDC_ROLE_CLAIM_REVIEWER: "reviewer"
      OIDC_ROLE_CLAIM_READER: "reader"
      OIDC_ACCESS_ATTRIBUTE_MAP: >
        {"given_name": "first_name", "family_name": "last_name", "realm_access": "realm_access"}
      OIDC_SECONDARY_PROVIDER_NAMES: "secondary"
      OIDC_RP_CLIENT_ID_SECONDARY: "am-storage-service-secondary"
      OIDC_RP_CLIENT_SECRET_SECONDARY: "example-secret-secondary"
      OIDC_OP_AUTHORIZATION_ENDPOINT_SECONDARY: "http://keycloak:8080/realms/secondary/protocol/openid-connect/auth"
      OIDC_OP_TOKEN_ENDPOINT_SECONDARY: "http://keycloak:8080/realms/secondary/protocol/openid-connect/token"
      OIDC_OP_USER_ENDPOINT_SECONDARY: "http://keycloak:8080/realms/secondary/protocol/openid-connect/userinfo"
      OIDC_OP_JWKS_ENDPOINT_SECONDARY: "http://keycloak:8080/realms/secondary/protocol/openid-connect/certs"
      OIDC_OP_LOGOUT_ENDPOINT_SECONDARY: "http://keycloak:8080/realms/secondary/protocol/openid-connect/logout"
      OIDC_OP_SET_ROLES_FROM_CLAIMS_SECONDARY: "true"
      OIDC_OP_ROLE_CLAIM_PATH_SECONDARY: "realm_access.roles"
      OIDC_ROLE_CLAIM_ADMIN_SECONDARY: "admin-secondary"
      OIDC_ROLE_CLAIM_MANAGER_SECONDARY: "manager-secondary"
      OIDC_ROLE_CLAIM_REVIEWER_SECONDARY: "reviewer-secondary"
      OIDC_ROLE_CLAIM_READER_SECONDARY: "reader-secondary"
      OIDC_ACCESS_ATTRIBUTE_MAP_SECONDARY: >
        {"given_name": "first_name", "family_name": "last_name", "realm_access": "realm_access"}
      OIDC_RP_SIGN_ALGO: "RS256"
    depends_on:
      keycloak:
        condition: service_started

  keycloak:
    image: "quay.io/keycloak/keycloak:26.5.4-0"
    command: ["start-dev", "--import-realm"]
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      KC_METRICS_ENABLED: "true"
      KC_LOG_LEVEL: "INFO"
    ports:
      - "8080:8080"
    volumes:
      - "./etc/keycloak/realm.json:/opt/keycloak/data/import/realm.json:ro"
