---

services:
  archivematica-acceptance-tests:
    build:
      context: "./submodules/archivematica-acceptance-tests"
      dockerfile: "Dockerfile"
      args:
        TARGET: "archivematica-acceptance-tests"
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
        PYTHON_VERSION: ${PYTHON_VERSION:-3.9}
    security_opt:
      - "seccomp:unconfined"
    volumes:
      - "./submodules/archivematica-acceptance-tests/:/src/"
      - "/dev/shm:/dev/shm"
      - "./submodules/archivematica-sampledata:/home/archivematica/archivematica-sampledata:ro"
      - "archivematica_pipeline_data:/var/archivematica/sharedDirectory:ro"
    links:
      - "nginx"
