from collections.abc import Mapping

from django.http import HttpRequest
from django.http import HttpResponseNotAllowed
from django.http import HttpResponseRedirect
from django.views.generic import View

class OIDCAuthenticationCallbackView(View):
    @staticmethod
    def get_settings(attr: str, *args: object) -> object: ...
    @property
    def failure_url(self) -> str: ...
    @property
    def success_url(self) -> str: ...
    def login_failure(self) -> HttpResponseRedirect: ...
    def login_success(self) -> HttpResponseRedirect: ...
    def get(self, request: HttpRequest) -> HttpResponseRedirect: ...

def get_next_url(request: HttpRequest, redirect_field_name: str) -> str | None: ...

class OIDCAuthenticationRequestView(View):
    OIDC_OP_AUTH_ENDPOINT: str
    OIDC_RP_CLIENT_ID: str

    def __init__(self, *args: object, **kwargs: object) -> None: ...
    @staticmethod
    def get_settings(attr: str, *args: object) -> object: ...
    def get(self, request: HttpRequest) -> HttpResponseRedirect: ...
    def get_extra_params(self, request: HttpRequest) -> Mapping[str, str]: ...

class OIDCLogoutView(View):
    @staticmethod
    def get_settings(attr: str, *args: object) -> object: ...
    @property
    def redirect_url(self) -> str: ...
    def post(self, request: HttpRequest) -> HttpResponseRedirect: ...
    def get(
        self, request: HttpRequest
    ) -> HttpResponseRedirect | HttpResponseNotAllowed: ...
