// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package sqlcmysql

import (
	"context"
	"database/sql"
)

type Querier interface {
	CleanUpActiveJobs(ctx context.Context) error
	CleanUpActiveSIPs(ctx context.Context) error
	CleanUpActiveTasks(ctx context.Context) error
	CleanUpActiveTransfers(ctx context.Context) error
	CleanUpAwaitingJobs(ctx context.Context) error
	CleanUpTasksWithAwaitingJobs(ctx context.Context) error
	CreateJob(ctx context.Context, arg *CreateJobParams) error
	CreateWorkflowUnitVariable(ctx context.Context, arg *CreateWorkflowUnitVariableParams) error
	ReadWorkflowUnitVariable(ctx context.Context, arg *ReadWorkflowUnitVariableParams) (sql.NullString, error)
}

var _ Querier = (*Queries)(nil)
