-- Delete views
DROP VIEW FileExtensions;
DROP VIEW FilesByUnit;
DROP VIEW PDI_by_unit;
DROP VIEW developmentAide_choicesDisplayed;
DROP VIEW jobDurationsView;
DROP VIEW lastJobsInfo;
DROP VIEW lastJobsTasks;
DROP VIEW processingDurationInformation2;
DROP VIEW processingDurationInformationByClient;
DROP VIEW processingDurationInformation;
DROP VIEW taskDurationsView;
DROP VIEW transfersAndSIPs;
