#!/bin/bash
userID=`id -u archivematica`

if [ "${userID}" = 333 ]; then
  echo "User archivematica exists"
else
  adduser --uid 333 --group --system --home /var/lib/archivematica/ archivematica
fi

sudo usermod -a -G audio archivematica
sudo chown -R archivematica:archivematica "/var/archivematica/"
sudo chown -R archivematica:archivematica "/var/archivematica/sharedDirectory/"
sudo chmod -R g+s "/var/archivematica/"
sudo chmod -R 664 "/var/archivematica/sharedDirectory" 
sudo find -L /var/archivematica/ -type d  | sudo xargs -IF chmod u+rwx,g+rwxt,o-rwx F


#Configure sudoers for mcp and client
echo "About to add archivematica sudoers file"
set -e
tmp="/tmp/archivematica-sudoers"
real="/etc/sudoers.d/archivematica"
echo "archivematica ALL=NOPASSWD:/bin/mv,/bin/chown,/bin/chmod,/usr/bin/find,/usr/bin/gs,/usr/bin/inkscape" > "${tmp}"
# Check validity
sudo visudo -c -f ${tmp}
if [ "$?" -eq "0" ]; then
    sudo chown root:root "${tmp}"
    sudo chmod 440 "${tmp}"
    sudo mv ${tmp} ${real}
fi
echo "archivematica sudoers file was added"

