#!/bin/sh
userID=`id -u archivematica`

if [ "${userID}" = 333 ]; then
  echo "User archivematica exists"
else
  adduser --uid 333 --group --system --home /var/lib/archivematica/ archivematica
fi

sudo usermod -a -G audio archivematica
sudo chown -R archivematica:archivematica "/var/archivematica/"
sudo chown -R archivematica:archivematica "/var/archivematica/sharedDirectory/"
sudo chmod -R g+s "/var/archivematica/"
sudo chmod -R 664 "/var/archivematica/sharedDirectory" 
sudo find -L /var/archivematica/ -type d  | sudo xargs -IF chmod u+rwx,g+rwxt,o-rwx F


#Configure sudoers for mcp and client
echo about to edit sudoers file
set -e
cd "$origDir"
tmp="./sudoers-`uuid`"
sudo cat /etc/sudoers > "./ETCsudoersBackup"
sudo grep -v archivematica  "/etc/sudoers" > "${tmp}"
sudo echo "archivematica ALL=NOPASSWD:/bin/mv,/bin/chown,/bin/chmod,/usr/bin/find,/usr/bin/gs,/usr/bin/inkscape" >> "${tmp}"
sudo chown 0:0 "${tmp}"
sudo chmod 440 "${tmp}"
sudo mv -f "${tmp}" /etc/sudoers
echo sudoers file was edited
#chown archivematica:archivematica /etc/archivematica/MCPServer/dbsettings
#chmod 700 /etc/archivematica/MCPServer/dbsettings
