from collections.abc import Callable
from typing import ClassVar

from django.contrib.auth.middleware import RemoteUserMiddleware
from django.contrib.auth.models import User
from django.http import HttpRequest
from django.http import HttpResponseBase

class ShibbolethRemoteUserMiddleware(RemoteUserMiddleware):
    header: ClassVar[str]

    def __init__(
        self,
        get_response: Callable[[HttpRequest], HttpResponseBase],
    ) -> None: ...
    def __call__(self, request: HttpRequest) -> HttpResponseBase: ...
    def process_request(self, request: HttpRequest) -> None: ...
    def make_profile(self, user: User, shib_meta: dict[str, object]) -> None: ...
    def setup_session(self, request: HttpRequest) -> None: ...
    def update_user_groups(self, request: HttpRequest, user: User) -> None: ...
    @staticmethod
    def parse_attributes(request: HttpRequest) -> tuple[dict[str, object], bool]: ...
    @staticmethod
    def parse_group_attributes(request: HttpRequest) -> list[str]: ...

class ShibbolethValidationError(Exception): ...
