#!/bin/sh

userID=`id -u archivematica`

if [ "${userID}" = 333 ]; then
  echo "User archivematica exists"
else
  adduser --uid 333 --group --system --home /var/lib/archivematica/ archivematica
fi

# use pip installed fido instead of os package version
update-alternatives --install /usr/bin/fido fido /usr/local/bin/fido 1

logdir=/var/log/archivematica/MCPClient
mkdir -p $logdir
chown -R archivematica:archivematica $logdir
chmod -R g+s $logdir
