# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import job_pb2 as job__pb2


class JobServiceStub(object):
    """Legacy compatible job status methods
  """

    def __init__(self, channel):
        """Constructor.

    Args:
      channel: A grpc.Channel.
    """
        self.CreatePackage = channel.unary_unary(
            "/JobService/CreatePackage",
            request_serializer=job__pb2.CreatePackageRequest.SerializeToString,
            response_deserializer=job__pb2.CreatePackageResponse.FromString,
        )
        self.ListSIPStatuses = channel.unary_unary(
            "/JobService/ListSIPStatuses",
            request_serializer=job__pb2.SIPStatusesRequest.SerializeToString,
            response_deserializer=job__pb2.SIPStatusesResponse.FromString,
        )
        self.ListTransferStatuses = channel.unary_unary(
            "/JobService/ListTransferStatuses",
            request_serializer=job__pb2.TransferStatusesRequest.SerializeToString,
            response_deserializer=job__pb2.TransferStatusesResponse.FromString,
        )
        self.GetUnitStatus = channel.unary_unary(
            "/JobService/GetUnitStatus",
            request_serializer=job__pb2.UnitStatusRequest.SerializeToString,
            response_deserializer=job__pb2.UnitStatusResponse.FromString,
        )
        self.GetProcessingConfig = channel.unary_unary(
            "/JobService/GetProcessingConfig",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=job__pb2.GetProcessingConfigResponse.FromString,
        )
        self.ApproveJob = channel.unary_unary(
            "/JobService/ApproveJob",
            request_serializer=job__pb2.ApproveJobRequest.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
        self.ApproveTransfer = channel.unary_unary(
            "/JobService/ApproveTransfer",
            request_serializer=job__pb2.ApproveTransferRequest.SerializeToString,
            response_deserializer=job__pb2.ApproveTransferResponse.FromString,
        )
        self.ApprovePartialReingest = channel.unary_unary(
            "/JobService/ApprovePartialReingest",
            request_serializer=job__pb2.ApprovePartialReingestRequest.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
        self.ListJobsAwaitingApproval = channel.unary_unary(
            "/JobService/ListJobsAwaitingApproval",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=job__pb2.ListJobsAwaitingApprovalResponse.FromString,
        )


class JobServiceServicer(object):
    """Legacy compatible job status methods
  """

    def CreatePackage(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListSIPStatuses(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListTransferStatuses(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetUnitStatus(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetProcessingConfig(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ApproveJob(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ApproveTransfer(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ApprovePartialReingest(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListJobsAwaitingApproval(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_JobServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "CreatePackage": grpc.unary_unary_rpc_method_handler(
            servicer.CreatePackage,
            request_deserializer=job__pb2.CreatePackageRequest.FromString,
            response_serializer=job__pb2.CreatePackageResponse.SerializeToString,
        ),
        "ListSIPStatuses": grpc.unary_unary_rpc_method_handler(
            servicer.ListSIPStatuses,
            request_deserializer=job__pb2.SIPStatusesRequest.FromString,
            response_serializer=job__pb2.SIPStatusesResponse.SerializeToString,
        ),
        "ListTransferStatuses": grpc.unary_unary_rpc_method_handler(
            servicer.ListTransferStatuses,
            request_deserializer=job__pb2.TransferStatusesRequest.FromString,
            response_serializer=job__pb2.TransferStatusesResponse.SerializeToString,
        ),
        "GetUnitStatus": grpc.unary_unary_rpc_method_handler(
            servicer.GetUnitStatus,
            request_deserializer=job__pb2.UnitStatusRequest.FromString,
            response_serializer=job__pb2.UnitStatusResponse.SerializeToString,
        ),
        "GetProcessingConfig": grpc.unary_unary_rpc_method_handler(
            servicer.GetProcessingConfig,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=job__pb2.GetProcessingConfigResponse.SerializeToString,
        ),
        "ApproveJob": grpc.unary_unary_rpc_method_handler(
            servicer.ApproveJob,
            request_deserializer=job__pb2.ApproveJobRequest.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        "ApproveTransfer": grpc.unary_unary_rpc_method_handler(
            servicer.ApproveTransfer,
            request_deserializer=job__pb2.ApproveTransferRequest.FromString,
            response_serializer=job__pb2.ApproveTransferResponse.SerializeToString,
        ),
        "ApprovePartialReingest": grpc.unary_unary_rpc_method_handler(
            servicer.ApprovePartialReingest,
            request_deserializer=job__pb2.ApprovePartialReingestRequest.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        "ListJobsAwaitingApproval": grpc.unary_unary_rpc_method_handler(
            servicer.ListJobsAwaitingApproval,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=job__pb2.ListJobsAwaitingApprovalResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "JobService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
