#!/bin/bash

# This file is part of Archivematica.
#
# Copyright 2010-2013 Artefactual Systems Inc. <http://artefactual.com>
#
# Archivematica is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Archivematica is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Archivematica.  If not, see <http://www.gnu.org/licenses/>.

# @package Archivematica
# @subpackage Ingest
# @author Joseph Perry <joseph@artefactual.com>
# @version svn: $Id$

#source /etc/archivematica/archivematicaConfig.conf
set -e
pidFile="/tmp/archivematicaMCPServer.pid"
logFile="/var/archivematica/sharedDirectory/archivematicaMCPServer.log"


startArchivematica() {
    echo "Starting"
    tmpDir="`pwd`"
    cd /usr/lib/archivematica/MCPServer/
    sudo -u archivematica twistd -y /usr/lib/archivematica/MCPServer/archivematicaMCP.py --pidfile "$pidFile" -l "$logFile" #--gid archivematica
    sudo -u archivematica chmod 755 "$pidFile"
    sudo -u archivematica chmod 755 "$logFile"
    echo PID: `cat "$pidFile"`
    cd "$tmpDir"
    echo "Started"
}

stopArchivematica() {
    echo "Stopping"
    "$0" status && kill `cat "$pidFile"`
    echo "Stopped"
}

case "$1" in
  start)
        startArchivematica
	;;
  stop)
        stopArchivematica
	;;

  reload|force-reload)
        stopArchivematica
        startArchivematica
	;;

  restart)
        stopArchivematica
        sleep 1
        startArchivematica
	;;

  status)
	#status_of_proc -p "$pidFile" /usr/bin/python /usr/bin/twistd && exit 0 || exit $?
	if [ -n "`cat "$pidFile" 2>/dev/null`" ]; then
			ps `cat "$pidFile"`
			exit 0
		else
			echo "Not running"
			exit 1
		fi

	;;

  *)
	echo "usage [start | stop | restart ]"
	exit 1
esac

exit 0
