#!/bin/sh

a2enmod wsgi

userID=`id -u archivematicadashboard`

if [ "${userID}" = 334 ]; then
  echo "User archivematicadashboard exists"
else
  adduser --uid 334 --group --system --home /var/lib/archivematica-django/ archivematicadashboard
fi

logdir=/var/log/archivematica/dashboard
mkdir -p $logdir
chown -R archivematicaDashboard:archivematica $logdir
chmod -R g+ws $logdir

#install dashboard requirements
pip install -r /usr/share/archivematica/dashboard/requirements.txt
# AM 1.1.0 and earlier did not set charset and collation on db properly
#this is required to allow syncdb to work properly
mysql -u archivematica -pdemo MCP -e 'alter database MCP CHARACTER SET utf8 COLLATE utf8_unicode_ci'
sudo -u archivematicaDashboard /usr/share/archivematica/dashboard/manage.py syncdb --settings='settings.common'

/etc/init.d/apache2 restart

#DEBHELPER#
