#!/bin/sh

a2enmod wsgi


logdir=/var/log/archivematica/dashboard
mkdir -p $logdir
chown -R archivematica:archivematica $logdir
chmod -R g+s $logdir

# TODO Remove this from the postinst of any version that is not updating Django
# Remove .pyo's so Django uninstalls properly (See https://github.com/pypa/pip/issues/2209)
echo "Removing Django's .pyo files to aid upgrade"
find /usr/local/lib/python2.7/dist-packages/django/ -name '*.pyo' -delete

# Install & upgrade dashboard requirements
pip install --upgrade -r /usr/share/archivematica/dashboard/requirements.txt
# AM 1.1.0 and earlier did not set charset and collation on db properly
#this is required to allow syncdb to work properly
mysql -u archivematica -pdemo MCP -e 'alter database MCP CHARACTER SET utf8 COLLATE utf8_unicode_ci'

# Fake migrations if necessary.  $2 is old version
if [[ $2 == '1.4.1'* ]]; then
    echo 'Faking 1.4.1 database setup'
    /usr/share/archivematica/dashboard/manage.py migrate locations 0001_initial --fake --settings='settings.common'
    echo 'Faking 1.4.1 data setup'
    /usr/share/archivematica/dashboard/manage.py migrate locations 0002_initial_data --fake --settings='settings.common'
fi

# Run migrations
/usr/share/archivematica/dashboard/manage.py migrate --settings='settings.common'

/etc/init.d/apache2 restart

userID=`id -u archivematicadashboard`

if [ "${userID}" = 334 ]; then
  echo "User archivematicadashboard exists"
else
  adduser --uid 334 --group --system --home /var/lib/archivematica-django/ archivematicadashboard
fi

#DEBHELPER#
