// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlcmysql

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.cleanUpActiveJobsStmt, err = db.PrepareContext(ctx, cleanUpActiveJobs); err != nil {
		return nil, fmt.Errorf("error preparing query CleanUpActiveJobs: %w", err)
	}
	if q.cleanUpActiveSIPsStmt, err = db.PrepareContext(ctx, cleanUpActiveSIPs); err != nil {
		return nil, fmt.Errorf("error preparing query CleanUpActiveSIPs: %w", err)
	}
	if q.cleanUpActiveTasksStmt, err = db.PrepareContext(ctx, cleanUpActiveTasks); err != nil {
		return nil, fmt.Errorf("error preparing query CleanUpActiveTasks: %w", err)
	}
	if q.cleanUpActiveTransfersStmt, err = db.PrepareContext(ctx, cleanUpActiveTransfers); err != nil {
		return nil, fmt.Errorf("error preparing query CleanUpActiveTransfers: %w", err)
	}
	if q.cleanUpAwaitingJobsStmt, err = db.PrepareContext(ctx, cleanUpAwaitingJobs); err != nil {
		return nil, fmt.Errorf("error preparing query CleanUpAwaitingJobs: %w", err)
	}
	if q.cleanUpTasksWithAwaitingJobsStmt, err = db.PrepareContext(ctx, cleanUpTasksWithAwaitingJobs); err != nil {
		return nil, fmt.Errorf("error preparing query CleanUpTasksWithAwaitingJobs: %w", err)
	}
	if q.createJobStmt, err = db.PrepareContext(ctx, createJob); err != nil {
		return nil, fmt.Errorf("error preparing query CreateJob: %w", err)
	}
	if q.createTransferStmt, err = db.PrepareContext(ctx, createTransfer); err != nil {
		return nil, fmt.Errorf("error preparing query CreateTransfer: %w", err)
	}
	if q.createUnitVarStmt, err = db.PrepareContext(ctx, createUnitVar); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUnitVar: %w", err)
	}
	if q.getLockStmt, err = db.PrepareContext(ctx, getLock); err != nil {
		return nil, fmt.Errorf("error preparing query GetLock: %w", err)
	}
	if q.readTransferLocationStmt, err = db.PrepareContext(ctx, readTransferLocation); err != nil {
		return nil, fmt.Errorf("error preparing query ReadTransferLocation: %w", err)
	}
	if q.readTransferWithLocationStmt, err = db.PrepareContext(ctx, readTransferWithLocation); err != nil {
		return nil, fmt.Errorf("error preparing query ReadTransferWithLocation: %w", err)
	}
	if q.readUnitVarStmt, err = db.PrepareContext(ctx, readUnitVar); err != nil {
		return nil, fmt.Errorf("error preparing query ReadUnitVar: %w", err)
	}
	if q.readUnitVarsStmt, err = db.PrepareContext(ctx, readUnitVars); err != nil {
		return nil, fmt.Errorf("error preparing query ReadUnitVars: %w", err)
	}
	if q.releaseLockStmt, err = db.PrepareContext(ctx, releaseLock); err != nil {
		return nil, fmt.Errorf("error preparing query ReleaseLock: %w", err)
	}
	if q.updateJobStatusStmt, err = db.PrepareContext(ctx, updateJobStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateJobStatus: %w", err)
	}
	if q.updateTransferLocationStmt, err = db.PrepareContext(ctx, updateTransferLocation); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateTransferLocation: %w", err)
	}
	if q.updateUnitVarStmt, err = db.PrepareContext(ctx, updateUnitVar); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUnitVar: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.cleanUpActiveJobsStmt != nil {
		if cerr := q.cleanUpActiveJobsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing cleanUpActiveJobsStmt: %w", cerr)
		}
	}
	if q.cleanUpActiveSIPsStmt != nil {
		if cerr := q.cleanUpActiveSIPsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing cleanUpActiveSIPsStmt: %w", cerr)
		}
	}
	if q.cleanUpActiveTasksStmt != nil {
		if cerr := q.cleanUpActiveTasksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing cleanUpActiveTasksStmt: %w", cerr)
		}
	}
	if q.cleanUpActiveTransfersStmt != nil {
		if cerr := q.cleanUpActiveTransfersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing cleanUpActiveTransfersStmt: %w", cerr)
		}
	}
	if q.cleanUpAwaitingJobsStmt != nil {
		if cerr := q.cleanUpAwaitingJobsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing cleanUpAwaitingJobsStmt: %w", cerr)
		}
	}
	if q.cleanUpTasksWithAwaitingJobsStmt != nil {
		if cerr := q.cleanUpTasksWithAwaitingJobsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing cleanUpTasksWithAwaitingJobsStmt: %w", cerr)
		}
	}
	if q.createJobStmt != nil {
		if cerr := q.createJobStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createJobStmt: %w", cerr)
		}
	}
	if q.createTransferStmt != nil {
		if cerr := q.createTransferStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createTransferStmt: %w", cerr)
		}
	}
	if q.createUnitVarStmt != nil {
		if cerr := q.createUnitVarStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUnitVarStmt: %w", cerr)
		}
	}
	if q.getLockStmt != nil {
		if cerr := q.getLockStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLockStmt: %w", cerr)
		}
	}
	if q.readTransferLocationStmt != nil {
		if cerr := q.readTransferLocationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing readTransferLocationStmt: %w", cerr)
		}
	}
	if q.readTransferWithLocationStmt != nil {
		if cerr := q.readTransferWithLocationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing readTransferWithLocationStmt: %w", cerr)
		}
	}
	if q.readUnitVarStmt != nil {
		if cerr := q.readUnitVarStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing readUnitVarStmt: %w", cerr)
		}
	}
	if q.readUnitVarsStmt != nil {
		if cerr := q.readUnitVarsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing readUnitVarsStmt: %w", cerr)
		}
	}
	if q.releaseLockStmt != nil {
		if cerr := q.releaseLockStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing releaseLockStmt: %w", cerr)
		}
	}
	if q.updateJobStatusStmt != nil {
		if cerr := q.updateJobStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateJobStatusStmt: %w", cerr)
		}
	}
	if q.updateTransferLocationStmt != nil {
		if cerr := q.updateTransferLocationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateTransferLocationStmt: %w", cerr)
		}
	}
	if q.updateUnitVarStmt != nil {
		if cerr := q.updateUnitVarStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUnitVarStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                               DBTX
	tx                               *sql.Tx
	cleanUpActiveJobsStmt            *sql.Stmt
	cleanUpActiveSIPsStmt            *sql.Stmt
	cleanUpActiveTasksStmt           *sql.Stmt
	cleanUpActiveTransfersStmt       *sql.Stmt
	cleanUpAwaitingJobsStmt          *sql.Stmt
	cleanUpTasksWithAwaitingJobsStmt *sql.Stmt
	createJobStmt                    *sql.Stmt
	createTransferStmt               *sql.Stmt
	createUnitVarStmt                *sql.Stmt
	getLockStmt                      *sql.Stmt
	readTransferLocationStmt         *sql.Stmt
	readTransferWithLocationStmt     *sql.Stmt
	readUnitVarStmt                  *sql.Stmt
	readUnitVarsStmt                 *sql.Stmt
	releaseLockStmt                  *sql.Stmt
	updateJobStatusStmt              *sql.Stmt
	updateTransferLocationStmt       *sql.Stmt
	updateUnitVarStmt                *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                               tx,
		tx:                               tx,
		cleanUpActiveJobsStmt:            q.cleanUpActiveJobsStmt,
		cleanUpActiveSIPsStmt:            q.cleanUpActiveSIPsStmt,
		cleanUpActiveTasksStmt:           q.cleanUpActiveTasksStmt,
		cleanUpActiveTransfersStmt:       q.cleanUpActiveTransfersStmt,
		cleanUpAwaitingJobsStmt:          q.cleanUpAwaitingJobsStmt,
		cleanUpTasksWithAwaitingJobsStmt: q.cleanUpTasksWithAwaitingJobsStmt,
		createJobStmt:                    q.createJobStmt,
		createTransferStmt:               q.createTransferStmt,
		createUnitVarStmt:                q.createUnitVarStmt,
		getLockStmt:                      q.getLockStmt,
		readTransferLocationStmt:         q.readTransferLocationStmt,
		readTransferWithLocationStmt:     q.readTransferWithLocationStmt,
		readUnitVarStmt:                  q.readUnitVarStmt,
		readUnitVarsStmt:                 q.readUnitVarsStmt,
		releaseLockStmt:                  q.releaseLockStmt,
		updateJobStatusStmt:              q.updateJobStatusStmt,
		updateTransferLocationStmt:       q.updateTransferLocationStmt,
		updateUnitVarStmt:                q.updateUnitVarStmt,
	}
}
