# Generated by Django 3.2.20 on 2023-08-18 00:48
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("fpr", "0038_use_uuidfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fpcommand",
            name="tool",
            field=models.ForeignKey(
                limit_choices_to={"enabled": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="fpr.fptool",
                to_field="uuid",
                verbose_name="the related tool",
            ),
        ),
    ]
