# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: processing.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='processing.proto',
  package='pb',
  syntax='proto3',
  serialized_pb=_b('\n\x10processing.proto\x12\x02pb\"\x93\x01\n\x03Job\x12\x1e\n\x06status\x18\x01 \x01(\x0e\x32\x0e.pb.Job.Status\"l\n\x06Status\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x15\n\x11\x41WAITING_DECISION\x10\x01\x12\x1a\n\x16\x43OMPLETED_SUCCESSFULLY\x10\x02\x12\x16\n\x12\x45XECUTING_COMMANDS\x10\x03\x12\n\n\x06\x46\x41ILED\x10\x04\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_JOB_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='pb.Job.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AWAITING_DECISION', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMPLETED_SUCCESSFULLY', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXECUTING_COMMANDS', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAILED', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=64,
  serialized_end=172,
)
_sym_db.RegisterEnumDescriptor(_JOB_STATUS)


_JOB = _descriptor.Descriptor(
  name='Job',
  full_name='pb.Job',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='pb.Job.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _JOB_STATUS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=172,
)

_JOB.fields_by_name['status'].enum_type = _JOB_STATUS
_JOB_STATUS.containing_type = _JOB
DESCRIPTOR.message_types_by_name['Job'] = _JOB

Job = _reflection.GeneratedProtocolMessageType('Job', (_message.Message,), dict(
  DESCRIPTOR = _JOB,
  __module__ = 'processing_pb2'
  # @@protoc_insertion_point(class_scope:pb.Job)
  ))
_sym_db.RegisterMessage(Job)


import grpc
from grpc.beta import implementations as beta_implementations
from grpc.beta import interfaces as beta_interfaces
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities
# @@protoc_insertion_point(module_scope)
