# Generated by Django 1.11.29 on 2023-08-11 16:29
import uuid

import main.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0081_package_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="jobuuid",
            field=main.models.UUIDField(
                db_column="jobUUID",
                default=uuid.uuid4,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="levelofdescription",
            name="id",
            field=main.models.UUIDField(
                db_column="pk", default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="metadataappliestotype",
            name="id",
            field=main.models.UUIDField(
                db_column="pk", default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="taxonomy",
            name="id",
            field=main.models.UUIDField(
                db_column="pk", default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="taxonomyterm",
            name="id",
            field=main.models.UUIDField(
                db_column="pk", default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="transfermetadatafield",
            name="id",
            field=main.models.UUIDField(
                db_column="pk", default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="transfermetadatafieldvalue",
            name="id",
            field=main.models.UUIDField(
                db_column="pk", default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="transfermetadataset",
            name="id",
            field=main.models.UUIDField(
                db_column="pk", default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="unitvariable",
            name="id",
            field=main.models.UUIDField(
                db_column="pk", default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
