# Generated by Django 5.2.16 on 2026-08-04 10:50

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0089_remove_job_subjobof"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="pk", primary_key=True, serialize=False),
                ),
                ("user_id", models.IntegerField(db_column="userID")),
                ("operation", models.CharField(max_length=100)),
                ("key_hash", models.CharField(db_column="keyHash", max_length=64)),
                (
                    "request_fingerprint",
                    models.CharField(db_column="requestFingerprint", max_length=64),
                ),
                ("result", models.JSONField()),
                (
                    "state",
                    models.CharField(
                        choices=[("pending", "Pending"), ("completed", "Completed")],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="createdAt"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(db_column="expiresAt", db_index=True),
                ),
            ],
            options={
                "db_table": "IdempotencyRecords",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_id", "operation", "key_hash"),
                        name="idempotency_user_operation_key_uniq",
                    )
                ],
            },
        ),
    ]
