name: Validate GitHub Action pinning

on:
  pull_request:
    paths:
      - ".github/workflows/**"
  push:
    branches:
      - "qa/**"
      - "stable/**"
    paths:
      - ".github/workflows/**"

permissions:
  contents: read

jobs:
  enforce-pinning:
    name: Enforce commit SHA pinning
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Ensure SHA-pinned Actions
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@3db98c0363e2fa5df3e1c4c471777a7c10b24cc9 # v5.0.5
